### ISSUE TITLE
Webhook Bug

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/Human-Connection-DiscordBot#17]
![grafik](https://user-images.githubusercontent.com/14029133/45763420-b2433080-bc30-11e8-9fbc-002a18c787b2.png)

Webhook seems to be double
Please look

**Comment by mimicc83** [comment]
did you setup another webhook earlier? If so we have 2 for this endpoint, one for organization HC and the one you've created. At least this is the only reason that came to my mind why these could double up.

**Comment by Lulalaby** [comment]
I transfered it from my own project, but my own project doesn't exsist anymore

**Comment by Lulalaby** [comment]
I only found the webhook in this repo

**Comment by Lulalaby** [comment]
Found the error 😄 
HC orga seems to have an webhook for the whole orga with all repos, and my repo has it's own too.
Removing it
Close #17
